### ISSUE TITLE
Do not use ID property

### ISSUE THREAD

**Issue by Fuco1** [kidd/org-gcal.el#100]
The ID property is special in org mode (see `org-id-get` and friends).  When posting an event with an existing ID, a duplicate is inserted:

```
:calendar-id: matus.goljer@gmail.com
:ETag:     "3195851531422000"
:ID:       0adsj51cvclf76nqilsf9mtak4/matus.goljer@gmail.com  <- added by gcal
:ID: d89e512b-e289-46b9-ac78-bc7ea2b7269a
```

We should either respect the original ID or use a different property, for example `GCAL_ID`.

**Comment by telotortium** [comment]
Yes, I've wanted to do this for a while. However, I'd like to continue to use the same overall approach as `org-id` to maintain the org-gcal event IDs. Most likely what I'll do is clone the needed parts of `org-id.el`, replacing references to the `:ID:` property with another property, and then use that in `org-gcal`.

**Comment by Fuco1** [comment]
I don't think I understand this part:

>  I'd like to continue to use the same overall approach as org-id to maintain the org-gcal event IDs. 

I looked through the code briefly and it seems it's not really using he org-id API very much, for example reading the ID is done simply by doing `(org-entry-get (point) "ID")` instead of `org-id-get-create`.  Maybe the code is obsolete and you want to switch to the org-id API?

I hoped `org-id` would have customizable property name but there it's also hard-coded.

**Comment by telotortium** [comment]
@Fuco1 What I mean is that I want to be able to search for ID locations in the same way as you can with `org-id`. I'll probably end up cloning the functions I need from `org-id` into a private library, changing the ID property, and maybe in the future trying to make a change upstream to let you change the property ID.
