### ISSUE TITLE
org-gcal-fetch duplicates all previously fetched events

### ISSUE THREAD

**Issue by japhir** [kidd/org-gcal.el#108]
Whenever I `org-gcal-fetch`, all the files that had been fetched previously are duplicated. If I fetch again, there are now 3 of them!

events do have their special ID's, which are also duplicated

```
* Beers with friends
:PROPERTIES:
:ETag:     "unique number"
:calendar-id: XX@gmail.com
:ID:       XXX@gmail.com
:END:
:org-gcal:
<2020-10-02 Fri 19:00-20:00>
```

there must be an issue with my config, here are the relevant lines:

```
 (use-package org-gcal
  :after org
  :bind (:map org-agenda-mode-map
                ("C-S-u" . org-gcal-fetch))  ;; same key as mu4e!
  :config
  (setq org-gcal-client-id "XXX.apps.googleusercontent.com"
	org-gcal-client-secret "XXXX"
	org-gcal-file-alist
	;; personal
	'(("XXX@gmail.com" . "~/org/calendars/gcal.org")
	 ("XXX@group.calendar.google.com" . "~/org/calendars/options.org")
	 ("XXX@group.calendar.google.com" . "~/org/calendars/societies.org")
	  ("XXX@group.calendar.google.com" . "~/org/calendars/sports.org")
	  ("XXX@group.calendar.google.com" . "~/org/calendars/university.org")
	  ("XX@gmail.com" . "~/org/calendars/fest.org"))))
```

**Comment by japhir** [comment]
It looks like perhaps the issue was with the last entry, which was a shared gmail calendar. I've no need for it to sync anymore and commented it out, now it seems to work ok!

**Comment by japhir** [comment]
It has now started duplicating everything again whenever I fetch, with the last calendar commented out.

**Comment by vnckppl** [comment]
I am encountering the same issue.

**Comment by japhir** [comment]
at first I thought it only duplicated repeating events, but just now it was also duplicating one-off events.. So i have no idea how this is caused or how to de-duplicate the events programmatically.

**Comment by japhir** [comment]
Based on @vnckppl's recommendation I tried removing my whole ~/org/calendars directory and syncing from scratch. This still results in duplicates for me, with some events single, some double, some even 4 times. No noticeable logic between repeating and non-repeating events.

**Comment by vnckppl** [comment]
> Based on @vnckppl's recommendation I tried removing my whole ~/org/calendars directory and syncing from scratch. This still results in duplicates for me, with some events single, some double, some even 4 times. No noticeable logic between repeating and non-repeating events.

Well, I was wrong. That solution seemed to work for me a few times, but now I am encountering the same issue with duplications of a large part, but not all, of the events on my calendar.

**Comment by mikecuoco** [comment]
I encountered the same issue after upgrading from version 20200809.2137, trying to downgrade now

**Comment by vnckppl** [comment]
I wrote an ugly work-around to flush and refetch my org cals. It needs to be called before you have run org-gcal, otherwise there are some settings in memory (that I could not easily find) which will interfere with the process.

```
(defun org-gcal-flush-and-refetch ()
  (interactive)
;;; Commentary:
  "Fix duplicates displayed in org gcal.
Delete agenda files, kill agenda buffers, remove token files, clear tokens in
Emacs, re-fetch all information with org-gcal."
;;; Code:
  ;; Time stamp
  (defvar ogf-dtstamp)
  (setq ogf-dtstamp (format-time-string "%Y%m%d_%H%M"))

  ;; Find agenda files
  (defvar ogf-agendapath "/Path/To/My/Folder/With/AgendaFiles")
  (defvar ogf-agendafiles)
  (setq ogf-agendafiles (directory-files ogf-agendapath nil ".org$"))

  ;; Set trash folder
  (defvar ogf-trashfolder)
  (setq ogf-trashfolder (concat "~/.Trash/org-gcal-fix_" ogf-dtstamp "/"))
  (make-directory ogf-trashfolder)

  ;; Clean up loop:
  (dolist (element ogf-agendafiles)
    ;; 1) Move agenda files to trash (don't really delete)
    (rename-file
     (concat ogf-agendapath "/" element)
     (concat ogf-trashfolder element))
    ;; 2) Close buffer
    (when (get-buffer element)
      (kill-buffer element))
    )

  ;; Close agenda buffer
  (when (get-buffer "*Org Agenda*")
    (kill-buffer "*Org Agenda*"))

  ;; Remove token file
  (rename-file
   "~/.emacs.d/org-gcal/.org-gcal-token"
   (concat ogf-trashfolder "/org-gcal-token"))

  ;; Clear sync tokens in Emacs
  (org-gcal-sync-tokens-clear)
  (unintern 'org-gcal-token-plist)

  ;; Set the browser function to external browser. This is required for
  ;; obtaining a token (see next step)
  (defvar ogf-current-browser browse-url-browser-function)
  (setq browse-url-browser-function 'browse-url-generic)
  
  ;; Refetch calendar (this should prompt for obtaining a token again)
  (org-gcal-fetch)

  ;; Restore browser function
  (setq browse-url-browser-function 'ogf-current-browser)
  
)
```

This will build the function org-gcal-flush-and-refetch that you can evaluate with M-:
Make sure to point to the folder where you store your .org agenda files (/Path/To/My/Folder/With/AgendaFiles).

**Comment by telotortium** [comment]
Hi everyone, I've made a bunch of improvements lately to the ID management. In particular, I fixed #100 to use a special property instead of the built-in Org `:ID:` property via the PR #124. One of the changes I made there was to more aggressively update the database of ID locations during `org-gcal` operations that update events. This might be enough to fix this issue. Could the people affected by this issue update to the latest `master` and try it out to see if any new duplicate events are created?

**Comment by japhir** [comment]
Hi, great that you're working on it again!

I've tried with the newest version on MELPA (`org-gcal-20210220.2040`). Is that the newest version?

I first tried running `org-gcal-fetch` to see if it would work, this resulted in the error:
```elisp
org-generic-id-update-id-locations: Wrong type argument: hash-table-p, nil
```
prior to the error there are some info messages such as:
```elisp
Finding :entry-id: locations (1/75 files): /home/japhir/org/inbox.org
```
Then I tried the above approach: deleted my agenda files, closed the agenda buffer, deleted the `.org-gcal-token` and called `org-gcal-fetch`. Also after restarting my emacsclient. Both result in the same error.

**Comment by telotortium** [comment]
OK, interesting.

Is `org-generic-id-locations` currently `nil`? If so, try running `org-generic-id-locations-load` and then `org-generic-id-update-id-locations` again. If that's the issue, I can patch `org-generic-id-update-id-locations` to fix this issue easily.

If it's not `nil`, could you show me what the contents are?

**Comment by HanshenWang** [comment]
Hello there,

I'm running into the same error. I don't know much elisp, but let me know what else I can do to help test. Prior to running "org-generic-id-locations-load" the value of "org-generic-id-locations" was nil.
I ran "org-generic-id-update-id-locations" afterwards in IELM and it resulted in

*** Welcome to IELM ***  Type (describe-mode) for help.

ELISP> (org-generic-id-locations-load)
#<hash-table equal 0/1 0x74545d>

ELISP> (org-generic-id-update-id-locations)
*** Eval error ***  Wrong number of arguments: ((t) (id-prop &optional files silent) "Scan relevant files for IDs.
Store the relation between files and corresponding IDs.
This will scan all agenda files, all associated archives, and all
files currently mentioned in `org-generic-id-locations'.
When FILES is given, scan also these files." (interactive "sID Property: ") (let* (id-locations (files (delete-dups (mapcar #'file-truename (cl-remove-if-not #'stringp (append (org-agenda-files t org-generic-id-search-archives) (if (symbolp org-generic-id-extra-files) (symbol-value org-generic-id-extra-files) org-generic-id-extra-files) org-generic-id-files files))))) (nfiles (length files)) (id-regexp (concat "^[	 ]*" (regexp-quote (format ":%s:" id-prop)) " +[^ ]")) (seen-ids nil) (ndup 0) (i 0)) (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (progn (make-local-variable 'delay-mode-hooks) (let ((delay-mode-hooks t)) (org-mode) (let ((--dolist-tail-- files)) (while --dolist-tail-- (let ((file (car --dolist-tail--))) (if (file-exists-p file) (progn (if silent nil (setq i (1+ i)) (message "Finding :%s: locations (%d/%d files): %s" id-prop i nfiles file)) (insert-file-contents file nil nil nil 'replace) (let ((ids nil) (case-fold-search t)) (let ((--mpom 1)) (save-excursion (if (markerp --mpom) (progn (set-buffer (marker-buffer --mpom)))) (save-excursion (save-restriction (widen) (goto-char (or --mpom (point))) (while (re-search-forward id-regexp nil t) (if (org-at-property-p) (progn (setq ids (cons (org-entry-get (point) id-prop) ids))))) (if ids (progn (setq id-locations (cons (cons (abbreviate-file-name file) ids) id-locations)) (let ((--dolist-tail-- ids)) (while --dolist-tail-- (let ((id (car --dolist-tail--))) (cond ((not (member id seen-ids)) (setq seen-ids (cons id seen-ids))) (silent nil) (t (message "Duplicate :%s: property %S" id-prop id) (setq ndup (1+ ndup)))) (setq --dolist-tail-- (cdr --dolist-tail--)))))))))))))) (setq --dolist-tail-- (cdr --dolist-tail--)))))))) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))) (puthash id-prop (org-generic-id--alist-to-hash id-locations) org-generic-id-locations) (org-generic-id-locations-save) (org-generic-id-locations-load) (if (and (not silent) (> ndup 0)) (progn (warn "WARNING: %d duplicate :%s: properties found, check *Messages* buffer" ndup id-prop))) (message "%d files scanned, %d files contain IDs, and %d :%s: IDs found." nfiles (length org-generic-id-files) (hash-table-count (gethash id-prop org-generic-id-locations)) id-prop) org-generic-id-locations)), 0
ELISP>

**Comment by HanshenWang** [comment]
I ended up rebuilding my google calendar from the ground up with a fresh installation of org-gcal. Everything works fine now.

Thanks for your continued work on org-gcal! Much appreciated.

**Comment by telotortium** [comment]
@japhir I've merged #126 to run `org-generic-id-locations-load` when the package is loaded, so hopefully that fixes your latest error.

**Comment by japhir** [comment]
That's great, seems to work now! New fetch asked me for new google authentication code (hidden behind the advanced tab because they say it's a security risk, unfortunately) but it works!

**Comment by japhir** [comment]
Also, fetching again a couple of times hasn't duplicated any events yet! Will close this for now, and re-open if I encounter the issue again.

Thank you so much! :)
