### ISSUE TITLE
Installation description doesn't match Google Developer's Console

### ISSUE THREAD

**Issue by DSMasterson** [kidd/org-gcal.el#112]
The description of what to do to install org-gcal doesn't match the Google Developer's Console that I see when I click on the link.  Because of that, I'm not clear on the steps in the Installation Guide.

Could someone clarify?

**Comment by kidd** [comment]
Until which step did it match? can you be a bit more explicit? also, maybe screenshots?

**Comment by DSMasterson** [comment]
It failed starting with step #1 - I'm just saying that the links to Google don't seem correct or are out-of-date.  For instance, the link to the Developer's Console is taking me to "APIs" page.  Therefore, I could find no Credentials link (stumbling around, I found it elsewhere, but I've forgotten where).  Therefore, 5-8 is confusing.  Also, I don't think 13 is right, but it is close.

Try the Installation steps.

**Comment by kidd** [comment]
Well, the link in #1 works for me. google redirects me to https://console.developers.google.com/cloud-resource-manager.  
The google console can be confusing, but I think everything is there

![sshot--2020-12-04--120301](https://user-images.githubusercontent.com/25607/101161522-d4b2a000-3628-11eb-9c98-ed525cb2e3a2.png)

**Comment by DSMasterson** [comment]
Duh!  I'm getting old and making simple mistakes... *sigh*
