### ISSUE TITLE
first run doesn't open any links, it gives error

### ISSUE THREAD

**Issue by mmohammadi9812** [kidd/org-gcal.el#125]
This is similar to #89 but for me, it doesn't get any events. First run, gives `Wrong type argument: hash-table-p, nil`  
I'm using doom emacs and here is my org-gcal settings:  
```lisp
(use-package! org-gcal
  :init
  (setq org-gcal-client-id "id.apps.googleusercontent.com"
        org-gcal-client-secret "secret"
        org-gcal-fetch-file-alist '(("email@gmail.com" . "~/Dropbox/org/events.org"))))
```

and here is the error buffer after running `M-x toggle-debug-on-error`: https://paste.ubuntu.com/p/K3bRDDR8tH/

I've enabled google calendar api and caldav api, I've published it (as suggestion of #116) and the oauth custom application type is desktop. I don't know what I'm doing wrong  
Thanks

**Comment by telotortium** [comment]
Hi, do you have this commit: https://github.com/kidd/org-gcal.el/commit/4bcbb35c6e53f8db551a0fc22aaf7caee2212809

It should have fixed the issue.

**Comment by telotortium** [comment]
I'm closing the issue. Feel free to respond if your issue is still not fixed with the latest version.
