### ISSUE TITLE
Getting org-refile missing error

### ISSUE THREAD

**Issue by francescopozzoni** [kidd/org-gcal.el#130]
Hi there, I'm using emacs-plus Version 27.1 (9.0) on Macos Mojave and getting this error when I run `(require 'org-gcal)`.

`Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "org-refile")
  require(org-refile)
  eval-buffer(#<buffer  *load*-945869> nil "/Users/myuser/.emacs.d/elpa/org-gcal-202..." nil t)  ; Reading at buffer position 724
  load-with-code-conversion("/Users/myuser/.emacs.d/elpa/org-gcal-202..." "/Users/myuser/.emacs.d/elpa/org-gcal-202..." nil t)
  require(org-generic-id)
  eval-buffer(#<buffer  *load*> nil "/Users/myuser/.emacs.d/elpa/org-gcal-202..." nil t)  ; Reading at buffer position 1456
  load-with-code-conversion("/Users/myuser/.emacs.d/elpa/org-gcal-202..." "/Users/myuser/.emacs.d/elpa/org-gcal-202..." nil t)
  require(org-gcal)
  eval((require 'org-gcal) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
`

I tried deleting and reinstalling the package from Melpa but I get a similar error during the installation too.

`
Compiling internal form(s) at Sun Feb 28 20:16:50 2021
Leaving directory ‘/Users/myuser/.emacs.d/elpa/org-gcal-20210227.111’

Compiling file /Users/myuser/.emacs.d/elpa/org-gcal-20210227.111/org-gcal.el at Sun Feb 28 20:16:50 2021
Entering directory ‘/Users/myuser/.emacs.d/elpa/org-gcal-20210227.111/’
org-gcal.el:43:1:Error: Cannot open load file: No such file or directory, org-refile

Compiling file /Users/myuser/.emacs.d/elpa/org-gcal-20210227.111/org-generic-id.el at Sun Feb 28 20:16:50 2021
org-generic-id.el:20:1:Error: Cannot open load file: No such file or directory, org-refile
`

**Comment by telotortium** [comment]
I'm not sure why your installation is running into this issue, but I've gone ahead and removed the `org-refile` import in #131

**Comment by francescopozzoni** [comment]
Without the import everything works fine, thank you. Hope to understand soon why it gave me this error...
