### ISSUE TITLE
rx-form: Unknown rx form ‘literal’

### ISSUE THREAD

**Issue by flavv** [kidd/org-gcal.el#132]
When I do sync or fetch by
M-x org-gcal-sync or M-x org-gcal-fetch :
rx-form: Unknown rx form ‘literal’
in *Message* buffer

.emacs.d/elpa/org-gcal-20210228.2038

**Comment by telotortium** [comment]
What version is your Emacs? What is the current value of `org-gcal-entry-id-property`? Could you run `M-x toggle-debug-on-error` and try again?

**Comment by flavv** [comment]
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.14) of 2020-03-26, modified by Debian

Its value is "entry-id"

Debugger entered--Lisp error: (error "Unknown rx form ‘literal’")
  signal(error ("Unknown rx form ‘literal’"))
  error("Unknown rx form `%s'" literal)
  rx-form((literal (format ":%s:" id-prop)) :)
  #f(compiled-function (x) #<bytecode 0xf23911>)((literal (format ":%s:" id-prop)))
  mapconcat(#f(compiled-function (x) #<bytecode 0xf23911>) (bol (0+ (any "\011 ")) (literal (format ":%s:" id-prop)) (1+ " ") (not (any " "))) nil)
  rx-and((seq bol (0+ (any "\011 ")) (literal (format ":%s:" id-prop)) (1+ " ") (not (any " "))))
  rx-form((seq bol (0+ (any "\011 ")) (literal (format ":%s:" id-prop)) (1+ " ") (not (any " "))))
  rx-to-string((seq bol (0+ (any "\011 ")) (literal (format ":%s:" id-prop)) (1+ " ") (not (any " "))) t)
  #f(compiled-function (&rest regexps) #<bytecode 0xf1b1d1>)((seq bol (0+ (any "\011 ")) (literal (format ":%s:" id-prop)) (1+ " ") (not (any " "))))
  (rx (seq bol (0+ (any "\011 ")) (literal (format ":%s:" id-prop)) (1+ " ") (not (any " "))))
  (let* (id-locations (files (delete-dups (mapcar (function file-truename) (cl-remove-if-not (function stringp) (append (org-agenda-files t org-generic-id-search-archives) (if ... ... org-generic-id-extra-files) org-generic-id-files files))))) (nfiles (length files)) (id-regexp (rx (seq bol (0+ (any "\011 ")) (literal (format ":%s:" id-prop)) (1+ " ") (not (any " "))))) (seen-ids nil) (ndup 0) (i 0)) (with-temp-buffer (delay-mode-hooks (org-mode) (dolist (file files) (when (file-exists-p file) (unless silent (cl-incf i) (message "Finding :%s: locations (%d/%d files): %s" id-prop i nfiles file)) (insert-file-contents file nil nil nil (quote replace)) (let ((ids nil) (case-fold-search t)) (org-with-point-at 1 (while ... ...) (when ids ... ...))))))) (puthash id-prop (org-generic-id--alist-to-hash id-locations) org-generic-id-locations) (org-generic-id-locations-save) (org-generic-id-locations-load) (when (and (not silent) (> ndup 0)) (warn "WARNING: %d duplicate :%s: properties found, check *Messages* buffer" ndup id-prop)) (message "%d files scanned, %d files contain IDs, and %d :%s: IDs found." nfiles (length org-generic-id-files) (hash-table-count (gethash id-prop org-generic-id-locations)) id-prop) org-generic-id-locations)
  org-generic-id-update-id-locations("entry-id")
  org-gcal-sync(t)
  org-gcal-fetch()
  funcall-interactively(org-gcal-fetch)
  call-interactively(org-gcal-fetch record nil)
  command-execute(org-gcal-fetch record)
  execute-extended-command(nil "org-gcal-fetch" "org-gcal-fet")
  funcall-interactively(execute-extended-command nil "org-gcal-fetch" "org-gcal-fet")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
