### ISSUE TITLE
How to hide user's google credentials

### ISSUE THREAD

**Issue by LorenRiccie** [kidd/org-gcal.el#148]
How would it possible to hide `org-gcal-client-id` and `org-gcal-client-secret` keys in an Emacs configuration file?

**Comment by telotortium** [comment]
This is out of the scope of `org-gcal`, but there are two ways:

- If you just want to hide the key from other users, create a file `org-gcal-secret-config.el` in your `.emacs.d` directory with contents like this:

  ```
  (setq org-gcal-client-id "ID" org-gcal-client-secret "SECRET")
  ```

  Make the file readable only by your user - on Linux or macOS, run `chmod 600 ~/.emacs.d/org-gcal-secret-config.el`. Then, load from your `init.el`:

  ```
  (load-file (expand-file-name "org-gcal-secret-config.el" user-emacs-directory))
  ```

- If you want to make sure the key is encrypted (e.g., if your file system isn't encrypted), use EasyPG to encrypt the `org-gcal-secret-config.el` file and load it into Emacs - see https://www.masteringemacs.org/article/keeping-secrets-in-emacs-gnupg-auth-sources#encrypting-data-with-a-key for more instructions.

**Comment by LorenRiccie** [comment]
Thank you.
