### ISSUE TITLE
Org-gcal & Agenda - Invalid Duration Format

### ISSUE THREAD

**Issue by carwin** [kidd/org-gcal.el#153]
## Environment
Linux (both Arch and Ubuntu 20.04), Emacs 26.3, `org-gcal` 20210421.2203

## Description
After a recent install on a fresh system, `org-gcal` works more or less perfectly on its own, but Agenda integration broke. The following message shows up any time I try to bring up an agenda view containing entries from one of my calendar files. Note the time range here is just an example:

```bash
org-duration-to-minutes: Invalid duration format: #("13:00-13:30" 0 11 (fontified nil line-prefix #("  " 0 2 (face org-indent)) wrap-prefix #("  " 0 2 (face org-indent)) ws-butler-chg chg org-category "MyCategory"))
```

The basic issue seems to be that either org, agenda, something somewhere in Emacs no longer handles time ranges separated by a single `-` and instead expects/requires double `-` characters to signify range.

## Workaround

Editing the org files containing the pulled entries and replacing instances of `13:00-13:30` with `13:00--13:30` resolves the issue. Again, the time range here is just an example, I needed to do this for every event `org-gcal` pulls in.

**Comment by podiki** [comment]
Noticed this too, but on my v28 (native comp) emacs and not v27.2, though there maybe be differences in the org-mode packages as well. This happened recently, but I'm not sure if it was from org-mode updating or, in my case, newer version of git emacs.

**Comment by HanshenWang** [comment]
This was a confirmed bug on the org mode mailing list. It is now patched. I had the same issue and updating to the latest org version solved the issue.

see: https://lists.gnu.org/archive/html/emacs-orgmode/2021-05/msg00938.html

**Comment by podiki** [comment]
Confirm it is fixed for me as well with current org-mode, thanks.

**Comment by carwin** [comment]
Haven't seen it since I updated Org. Thanks for the tip @HanshenWang.
