### ISSUE TITLE
`Wrong type argument: stringp, nil` error when run `org-gcal-sync`

### ISSUE THREAD

**Issue by noghartt** [kidd/org-gcal.el#162]
When run `M-x org-gcal-sync` I'm having an error, the error message is: `Wrong type argument: stringp, nil`.

I follow the instructions on [Installation](https://github.com/kidd/org-gcal.el#installation), but I don't know if I'm doing something wrong. It creates the `token.gpg` as well, but not sucessfully sync with Google Calendar.

I'm using Doom Emacs, with [calendar module](https://github.com/hlissner/doom-emacs/blob/develop/modules/app/calendar/README.org).

**Comment by telotortium** [comment]
Hi, can you try the debugging instructions:
https://github.com/kidd/org-gcal.el#debugging

Unfortunately I can't much with that error message alone.

**Comment by noghartt** [comment]
> Hi, can you try the debugging instructions:
> https://github.com/kidd/org-gcal.el#debugging

I think I found this behavior strange, because apparently when I try to debug with the `M-x org-gcal-toggle-debug` this option doesn't appear in the "Emacs Commands".

There aren't nothing simmilar to `org-gcal-toggle-debug` command. There's other way to debug this?

**Comment by telotortium** [comment]
Doom probably doesn't have the latest version yet.

You can copy the definition into your *scratch* buffer and eval it.

**Comment by noghartt** [comment]
IDK how, but it's work now!

So, I'm closing this issue! Thanks for you attention!
