### ISSUE TITLE
Getting error after today's org-gcal update

### ISSUE THREAD

**Issue by vnckppl** [kidd/org-gcal.el#207]
I just updated org-gcal via melpa and now it does not sync with gmail anymore. In the messages buffer, the following shows up:

```
Log in to your account for Emacs in your browser window
Contacting host: oauth2.googleapis.com:443
deferred error : (wrong-number-of-arguments #<subr seconds-to-time> 2)
```

When I sync org-gcal, it opens the google calendar webpage and let's me select my account. It then also shows me the message in the browser:

`Authentication token successfully obtained by Emacs! You may close this page now.`

But, then, emacs gives the error: 

`deferred error : (wrong-number-of-arguments #<subr seconds-to-time> 2)`

org-gcal was working correctly before this update and the following variables are all set and have not been changed before or after the update:
org-gcal-local-timezone
org-gcal-client-id
org-gcal-client-secret
org-gcal-fetch-file-alist

Is there anything I need to change to my config to make org-gcal work again?

**Comment by telotortium** [comment]
Let me debug this today

**Comment by telotortium** [comment]
@vnckppl What version of Emacs are you running?

**Comment by vnckppl** [comment]
> @vnckppl What version of Emacs are you running?

`GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-10-20`

**Comment by telotortium** [comment]
@vnckppl try patching your installation with my change in https://github.com/kidd/org-gcal.el/pull/208

**Comment by telenieko** [comment]
> @vnckppl try patching your installation with my change in #208

Fixed the error for me, my version:

> GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.16.0) of 2022-11-14

**Comment by vnckppl** [comment]
Thanks, this is working for me now.
