### ISSUE TITLE
deferred error "oauth2-auto: Unknown provider: org-gcal"

### ISSUE THREAD

**Issue by mfuchs1** [kidd/org-gcal.el#209]
Hello,

org-gcal was working fine until now.
I've updated org-gcal via melpa and I got this error message when running org-gcal-fetch or org-gcal-sync:

deferred error : (error "oauth2-auto: Unknown provider: org-gcal")

I'm using GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)
 of 2022-09-12

OS: Manjaro KDE 22.0.0

Thanks for your help.

**Comment by telenieko** [comment]
Try calling `(org-gcal-reload-client-id-secret)` after setting the `org-gcal-client-**` variables.

**Comment by mfuchs1** [comment]
Yes, thank you! That did the trick. org-gcal is working again. I can fetch events from google calendar and post events from org-mode to google. It's even better - there are no 

``` "Received HTTP 412 ETag stale for will averwirte this entry with event from server" ``` 

messages anymore. Thank you. I think you can close this issue.

**Comment by telotortium** [comment]
@mfuchs1 Did you see the warning "org-gcal: must set ‘org-gcal-client-id’ and ‘org-gcal-client-secret’ for this package to work. Please run ‘org-gcal-reload-client-id-secret’ after setting these variables."? I thought I detected this case [here](https://github.com/kidd/org-gcal.el/blob/0d98b30249ecfa7f6b1bffdb20f7b864742652b2/org-gcal.el#L2175-L2179).

**Comment by mfuchs1** [comment]
> @mfuchs1 Did you see the warning "org-gcal: must set ‘org-gcal-client-id’ and ‘org-gcal-client-secret’ for this package to work. Please run ‘org-gcal-reload-client-id-secret’ after setting these variables."? I thought I detected this case [here](https://github.com/kidd/org-gcal.el/blob/0d98b30249ecfa7f6b1bffdb20f7b864742652b2/org-gcal.el#L2175-L2179).

No, I didn't see this warning - I'm sorry. I've set the  ‘org-gcal-client-id’ and ‘org-gcal-client-secret’ in my init.el - already before this new update. The  ‘org-gcal-reload-client-id-secret’ resolved the issue.

**Comment by telotortium** [comment]
That's interesting, because with both ‘org-gcal-client-id’ and ‘org-gcal-client-secret’ set, ‘org-gcal-reload-client-id-secret’ should have automatically been called when the package was loaded (I just tested it, and I can confirm ‘org-gcal-reload-client-id-secret’ was called). Perhaps Melpa upgrades don't automatically re-evaluate the package somehow? I tend to upgrade in one of two ways, since I use Doom Emacs:

1. Doom downloads and recompiles the files. Then, I usually restart Emacs.
2. I make a change to `org-gcal` while developing and then call `eval-buffer`.

**Comment by i-oliva** [comment]
@telotortium may I ask how do you have it configured with doom? I'm not sure how to call `org-gcal-reload-client-id-secret` with doom

**Comment by vnckppl** [comment]
Thanks for working on this. It works for me now.
