### ISSUE TITLE
oauth2-auto fails to recognize oauth2-auto-plstore correctly

### ISSUE THREAD

**Issue by franburstall** [kidd/org-gcal.el#215]
As of updating `org-gcal` this morning, `(org-gcal-sync)` errors with
```
deferred error : (error "oauth2-auto: Unknown provider: org-gcal")
```
Doubtless, this is because I need to set things up for the new `oauth-auto` mechanisms but I have failed to find any instructions on how to do that.  Where should I look?

**Comment by telotortium** [comment]
Please try restarting Emacs.

**Comment by franburstall** [comment]
> Please try restarting Emacs.

No change (in fact I always restart after  updating packages).

**Comment by telotortium** [comment]
What's the value of the variable `oauth2-auto-additional-providers-alist` on your system (please redact client ID and secret)?

**Comment by franburstall** [comment]
It is `nil`.

**Comment by telotortium** [comment]
Try running the function `org-gcal-reload-client-id-secret`.

**Comment by franburstall** [comment]
That gets me further but not all the way there.  Having fired `org-gcal-reload-client-id-secret`, a subsequent call to `org-sync-gcal` triggers the authorisation dialogue with google and I see a screen on the browser saying 

> Authentication token successfully obtained by Emacs! You may close this page now.

I then get prompted to create a password for plstore.  I do this and then get a warning:

> Buffer  plstore /home/fran/.emacs.d/oauth2-auto.plist modified; kill anyway? 

I reply `n` having no understanding of what is going on and finally get an error

> deferred error : (error "BUG: Attempted to write ‘oauth2-auto’ keys to /home/fran/.emacs.d/oauth2-auto.plist, not ‘oauth2-auto-plstore’ (~/.emacs.d/oauth2-auto.plist).  Please report to https://github.com/rhaps0dy/emacs-oauth2-auto/issues/6.")

FWIW `~` is `/home/fran`.

**Comment by telotortium** [comment]
Need to merge https://github.com/telotortium/emacs-oauth2-auto/pull/13 into org-gcal.

**Comment by telotortium** [comment]
@franburstall This should be fixed with the most recent version.

**Comment by d-miketa** [comment]
I have the exact same issue on a recent version of org-gcal, unfortunately.
