### ISSUE TITLE
Make gcal work without projects

### ISSUE THREAD

**Issue by drym3r** [kidd/org-gcal.el#22]
Hi
I have a work google account and it seems I can't freely create google projects, since those are shared with my coworkers and link it with a billing account.
Is there a way to use org-gcal without the project?

**Comment by kidd** [comment]
If I understand this correctly, you should be able to create a project for your personal account, and then, from your work's calendar, give persmissions to your personal token

**Comment by kidd** [comment]
Any news on that? did it work?

**Comment by drym3r** [comment]
As we spoke in private, it seems it can't be done. Thanks anyway!
