### ISSUE TITLE
[Bug] Deferred error  Oauth2-auto: Unknown Provider

### ISSUE THREAD

**Issue by wakatara** [kidd/org-gcal.el#224]
I've used org-gcal in the past and returned to using emacs org-mode after some time. I am trying to get org-gcal to pull my calendar but am getting a `deferred error : (error: "oauth2 - auto: Unknown provider: org-gcal` when I initiate the `org-gcal-fetch` command for the first time.

(I named the google GCP project `org-gcal` just to avoid confusion )

I *believe* I've followed all the setup instructions correctly - consent screen, (not the first time and created a new project for it and went step by step through the list in the readme. 

I do note a change was made last month adding in ouath2-auth so just wondering it's something to do with that. 

My setup in case people think it is something to do with that (disabled auto-fetch and sync etc on launch): 

```elisp
(use-package org-gcal
  :straight t
  :config
  (setq org-gcal-client-id "<redacted>"
   org-gcal-client-secret "<redacted>"
   org-gcal-file-alist '( ("xxxx@xxxxxxx.com" . "~/Documents/org/logs/calw.org")
                         )))
  ;; (add-hook 'org-agenda-mode-hook (lambda () (org-gcal-fetch) ))
  ;; (add-hook 'org-capture-after-finalize-hook (lambda () (org-gcal-sync) ))
  (setq plstore-cache-passphrase-for-symmetric-encryption t)
```

Any ideas? 

thanks!
Daryl.

**Comment by mpereira** [comment]
I see the same.

The `"oauth2 - auto: Unknown provider: org-gcal"` error goes away after `M-x org-gcal-reload-client-id-secret`, but then I see the behavior reported in this comment: https://github.com/kidd/org-gcal.el/issues/213#issuecomment-1365756835

I get the passphrase prompt, but Emacs freezes after selecting y/n on `Buffer plstore /Users/till/.emacs.d/oauth2-auto.plist modified; kill anyway? (y or n)`.

**Comment by benthamite** [comment]
FWIW, I'm also encountering this problem, but `M-x org-gcal-reload-client-id-secret` fixes it without causing the issue in the comment @mpereira references (or causing any other problems).

**Comment by child404** [comment]
For me `M-x org-gcal-reload-client-id-secret` didn't help. Emacs starts freezing after that

**Comment by wakatara** [comment]
> FWIW, I'm also encountering this problem, but `M-x org-gcal-reload-client-id-secret` fixes it without causing the issue in the comment @mpereira references (or causing any other problems).

But do you already have an existing client-id-secret (in other words, a previously working install?).

**Comment by wakatara** [comment]
I just rebuilt org-gcal completely and I now seem to have it working though it did need to nuke the plstore. I am just going to use it for pull (rather than push) events, but for whatever reason, 29.0.60 upgrade seemed to help this (or I somehow had an older package that did not get rebuilt.).

Thanks as always for the hard work of the devs working on this. It does seem a bit magic to have gcal in my emacs.  =]
