### ISSUE TITLE
Emacs prompts for "Username [for https://oauth2.googleapis.com/token]"

### ISSUE THREAD

**Issue by Q-Tran** [kidd/org-gcal.el#233]
I followed the readme instructions, but I don't see a section where I make any sort of username or password. Using my google account username and password doesn't seem to work as well. What credentials am I using to log in?

This is the error I get:

deferred error : (error "OAuth error.  Request: ((client_id . \"deleted for privacy.apps.googleusercontent.com\")
 (client_secret . \"deleted for privacy")
 (redirect_uri . \"http://localhost:40223/\")
 (code . \"4/0AVHEtk4VkUMl0sGcaz626uyo7UF-_m8GKFkED6RV3HPRSNqbbdqQeNkZd3sEElP4iwZ3RA\")
 (grant_type . \"authorization_code\")
 (code_verifier . \"g0xOX9A9k00MpUAW6_WctYCmeENYmO2UEpnUQGI8xR1\"))
.  Response: ((error . \"invalid_request\")
 (error_description . \"Credentials in post body and basic Authorization header do not match\"))
")

**Comment by telotortium** [comment]
I'll take a look. Are you creating credentials for an external application on the Google Developers Console?

**Comment by Q-Tran** [comment]
I had entered in the credentials wrong. I meant to close this out. I apologize. I am getting another error and not sure how to deal with it, and open another issue
