### ISSUE TITLE
Initial properties are not properly handled, resulting in local duplicate events

### ISSUE THREAD

**Issue by barryridge** [kidd/org-gcal.el#25]
If I add an event such as this one:
```elisp
* Test Event 1
  :PROPERTIES:
  :LOCATION: Location 1
  :END:
  <2018-12-06 Thu>
```
after using either `org-gcal-post-at-point` or `org-gcal-sync`, the result is as follows:
```elisp
* Test Event 1
  :PROPERTIES:
  :LOCATION: Location 1
  :LINK: [[https://www.google.com/calendar/event?eid=xxx][Go to gcal web page]]
  :ID: xxx
  :END:

  <2018-12-06 Thu>

  :PROPERTIES:
  :LOCATION: Location 1
  :END:
  <2018-12-06 Thu>
```

If, on the other hand, I drop the properties altogether from the entry as follows:
```elisp
* Test Event 2
  <2018-12-06 Thu>
```
and then run `org-gcal-sync`, I get the following:
```elisp
* Test Event 2
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=xxx][Go to gcal web page]]
  :ID: xxx
  :END:

  <2018-12-06 Thu>
```

The `Test Event 1` case leaves duplicate events in the local `org` file (as you can see from the above) but *not* in the Google calendar.  Nevertheless, it is still quite a nuisance. One workaround, that works in the case of `Test Event 1`, is to just delete the trailing properties and timestamp and re-sync.  Another workaround, that works in the case of `Test Event 2` is to just add the `:LOCATION:` property to the updated event after the sync, once the `:ID:` and `:LINK:` properties have been added, then re-sync.

Note that I am using the [google-calendar-layer](https://github.com/mhkc/google-calendar-layer) (or at least [my own working fork](https://github.com/barryridge/google-calendar-layer) of it), as well as multiple calendars.  I would gladly dig into this a bit further myself, but I'm afraid my E-Lisp skills are not quite up to the challenge, currently.

**Comment by phrxmd** [comment]
I fixed that for myself in https://github.com/myuhe/org-gcal.el/pull/122. It's a simple change to the regexp that recognizes the property block. Check if it fixes it for you.

**Comment by phrxmd** [comment]
Ported the change to this branch, see https://github.com/kidd/org-gcal.el/pull/27.

**Comment by barryridge** [comment]
Just confirmed that your merged PR is working for me now that it has been updated on melpa.  Thank you very much @phrxmd

**Comment by yangsheng6810** [comment]
I am having this issue with `org-capture`. I typed the following in `org-capture` and finish.
```
* Yet another org-gcal event
  :PROPERTIES:
  :LOCATION: 1110 Kim Engineering Building
  :END:

  <2019-04-23 二 16:35>
```
What I get after it automatically post the item:
```
* Yet another org-gcal event
  :PROPERTIES:
  :LOCATION: 1110 Kim Engineering Building
  :END:

  <2019-04-23 二 16:35>

  <2019-04-23 二 16:35>
```
