### ISSUE TITLE
Current status for supporting multiple accounts

### ISSUE THREAD

**Issue by pj-paul** [kidd/org-gcal.el#33]
Hi all,

Wanted to know the current status for syncing multiple gmail accounts? 
Is this supported? How can I set this up? 

I'd seen this path in the old repo, but wasn't sure how to set up things at my end. https://github.com/myuhe/org-gcal.el/pull/72

**Comment by kidd** [comment]
Hi @pj-paul. Here's the way to synch multiple calendars. https://github.com/kidd/org-gcal.el#multiple-accounts

What you do is to share many calendars with one account.
