### ISSUE TITLE
Error during first time fetching Google calendar events.

### ISSUE THREAD

**Issue by csevast** [kidd/org-gcal.el#35]
After singing in and copying the code into Emacs, an error raised:

Searching for program: No such file or directory, curl

My operating system is Windows 10.

**Comment by kidd** [comment]
org-gcal depends on curl. you can get it for your OS in https://curl.haxx.se/windows/

**Comment by csevast** [comment]
Thank you even if I fixed it in a different way.

**Comment by csevast** [comment]
Hello kidd,

My first experience problems continue to insist. In the Google Developer's Console I created a Project, I enabled in it the Google Calendar API, I created credentials with a Client ID with its Client Secret, I collected the Calendar ID from my Google Calendar, I set the settings in my `init.el` file, I executed `M-x org-gcal-fetch`, I singed in my account after some warnings about safety and allowed my Google account to be accessed, I inserted the copied code from the browser to Emacs input, and an error raised with the followings messages:
```
REQUEST [error] Error (error) while connecting to https://www.googleapis.com/oauth2/v3/token.
deferred:resignal: Symbol’s value as variable is void: marker 
```
Before reporting the issue I tried to find any faults in my applied process and settings, again and again, but I didn't find something wrong. What the problem can be?

**Comment by telotortium** [comment]
Try `(setq deferred:debug-on-signal t)` - that might produce a stack trace

**Comment by csevast** [comment]
Unfortunately nothing more produced.

**Comment by csevast** [comment]
Something more,

When I try to fetch, Google warns me that the "The App isn't verified" and I have to grant permission every time I evaluate `org-gcal-fetch` or `org-gcal-sync`. The Emacs error message is the same for both functions.
