### ISSUE TITLE
Problem with coding-system

### ISSUE THREAD

**Issue by sdaaish** [kidd/org-gcal.el#41]
I get this error-message when syncing with org-gcal:

    These default coding systems were tried to encode text
    in the buffer ‘ *temp file*’:
      (utf-8 (127 . 4194243) (128 . 4194212))
    However, each of them encountered characters it couldn’t encode:
      utf-8 cannot encode these: � �
    
    Click on a character (or switch to this window by ‘M-x other-window’
    and select the characters by RET) to jump to the place it appears,
    where ‘C-u C-x =’ will give information about it.
    
    Select one of the safe coding systems listed below,
    or cancel the writing with C-g and edit the buffer
       to remove or modify the problematic characters,
    or specify any other coding system (and risk losing
       the problematic characters).
    
      raw-text no-conversion

with this in a temp-buffer:

    {"start":{"dateTime":"2019-05-21T05:00:00Z","date":null},"end":{"dateTime":"2019-05-21T05:10:00Z","date":null},"summary":"Sophämtning","location":null,"description":null}

Add a picture that shows this since the text gets encoded in Github.

This worked before the summer and I don't know what exactly changed between the working and non working versions.

Apparently it is the characters `å,ä,ö` that don't get converted correctly.

If I clean out my `gcal.org-file` and do a fresh synchronization, it works. But if I synchronize directly after that I get the error message above. I read somewhere that it might be related to double encoding, but I dont know if this is the issue here.

Versions:

-   Emacs: `GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-08-15`
-   Org-gcal: `20190812.951`
-   Org: `Org mode version 9.2.5 (9.2.5-1-gff6508-elpa @ *home/sdaa*.emacs.d/elpa/org-20190812/)`

See also: [StackExchange](https://emacs.stackexchange.com/questions/51953/utf-8-error-everytime-org-gcal-sync-entries)
![2019-08-16 (1)_LI](https://user-images.githubusercontent.com/19372022/63172997-38354a80-c03f-11e9-9d4b-ec04d999e24b.jpg)

**Comment by telotortium** [comment]
This looks very similar to a bug I saw recently in emacs-ycmd: https://github.com/abingham/emacs-ycmd/issues/496#issuecomment-518811714. The workaround is to tell request to use url-retrieve instead of curl. For me, I haven't seen it on org-gcal, but only o

**Comment by dickmao** [comment]
The default encoding for tkf/emacs-request#85 changed from binary to utf-8.  The solution is to explicitly set `:encoding 'binary` in the `request` call.

Changing the backend from `curl` to `url-retrieve` ventures into unexplored and likely very buggy territory.

I was about to make this small fix, but upgrading to the latest master from 3874040 (April 2019) imploded my org-agenda.  See #47.  Thanks.

**Comment by sdaaish** [comment]
I did try to fix this with your suggestion but modified for gcal. But it didn't change anything. But I'm not sure if I did it correctly, not an expert in emacs-lisp. I will need more instructions but I'm happy to test whatever you can come up with.

This was my test (that didn't change anything):
```emacs-lisp
(defun my-gcal--request-url-retrieve (f &rest args)
  "Change ‘request-backend’ in ‘gcal--request’ to ‘url-retrieve’.

Work around https://github.com/abingham/emacs-gcal/issues/496.
"
  (let ((request-backend 'url-retrieve))
    (apply f args)))
(advice-add 'org-gcal--get-event :around #'my-gcal--request-url-retrieve)
```

**Comment by dickmao** [comment]
Please don't use this fix.  You can try `M-x package-refresh-contents RET` and `M-x package-install RET request` to get the latest tkf/emacs-request library that will likely fix the problem.

**Comment by telotortium** [comment]
@dickmao How will getting the newest tkf/emacs-request fix the problem? Did they switch the default encoding back to binary?

**Comment by dickmao** [comment]
No, but it is my hope that [this patch](https://github.com/tkf/emacs-request/commit/2e9d48cc329a491dda809449d1da2052125f6b6d) circumvents the ugly "Select coding system" dialogue being reported in this issue.

**Comment by sdaaish** [comment]
I have the latest packages from Melpa, but still have the same problem.

    request            20190819.1735 installed
    request-deferred   20181129.317  dependency

The easiest way to get around this right now is to just press *Enter* on the question(s), (raw-text), and then do a `revert-buffer-with-coding-system`. Then the file looks OK.

**Comment by dickmao** [comment]
You're right -- I reproduced your issue.  My patch failed.

I redid the patch in tkf/emacs-request#136.  If you still have the forbearance, I'd try again with the latest melpa request library.

**Comment by sdaaish** [comment]
I upgraded *request* to `20190901.1539` and then it works for me. No errors at all. So I would say that fixed it. Thanks

**Comment by lbkvu** [comment]
I still have the same problem after using the latest version of `request`

```
  request            20200117.410  dependency            Compatible layer for URL request in Emacs
  request-deferred   20181129.317  dependency            Wrap request.el by deferred
```
I'm using Emacs on Windows
Could you please help?

**Comment by dickmao** [comment]
Two questions.  Go to `*scratch*` buffer, and `C-x C-e` after the closing parenthesis of the following s-expression.  Does it reproduce the error?

```
(let ((buffer-file-coding-system 'utf-8-dos))
  (request
    "http://httpbin.org/post"
    :type "POST"
    :data `(("latin" . ,(with-temp-buffer
                          (dotimes (_i 3)
                            (insert-char #xea))
                          (buffer-string))))
    :parser 'json-read
    :success (cl-function
              (lambda (&key data &allow-other-keys)
                (message "I sent: %S" (assoc-default 'form data))))))
```

C-x C-e after the closing parenthesis of the following.  What does it say?

```
(mapcar #'package-desc-dir (cdr (assq 'request package-alist)))
```

**Comment by lbkvu** [comment]
> ```
> (let ((buffer-file-coding-system 'utf-8-dos))
>   (request
>     "http://httpbin.org/post"
>     :type "POST"
>     :data `(("latin" . ,(with-temp-buffer
>                           (dotimes (_i 3)
>                             (insert-char #xea))
>                           (buffer-string))))
>     :parser 'json-read
>     :success (cl-function
>               (lambda (&key data &allow-other-keys)
>                 (message "I sent: %S" (assoc-default 'form data))))))
> ```
Its output in `*Message*` buffer is
```
#s(request-response nil nil nil nil nil "http://httpbin.org/post" nil (:type "POST" :data "latin=%C3%AA%C3%AA%C3%AA" :parser json-read :success (lambda (&rest --cl-rest--) "

(fn &key DATA &allow-other-keys)" (let* ... ...)) :error #[128 "ÂÀÃÁ\"\"" [request-default-error-callback ... apply append] 6 "

(fn &rest ARGS2)"] :url "http://httpbin.org/post" ...) #<buffer  *request curl*> nil nil ...)
I sent: ((latin . "êêê"))
```

> ```
> (mapcar #'package-desc-dir (cdr (assq 'request package-alist)))
> ```
Its output is `("c:/Users/William/AppData/Roaming/.emacs.d/elpa/request-20200117.410")`

**Comment by dickmao** [comment]
I don't know the answer.  I'm sorry.

My only suggestion is immediately before you trigger the problem, `C-u M-. select-safe-coding-system`, then `C-u C-M-x` anywhere in that function's body.  Then trigger the problem, and step through the function with SPC.  For whatever reason it's getting to `select-safe-coding-system-interactively` because `coding-system` is never assigned.
