### ISSUE TITLE
Read and respect timezone

### ISSUE THREAD

**Issue by michaelcadilhac** [kidd/org-gcal.el#48]
In `org-gcal-sync`, the timezone of the calendar, accessible via `(plist-get data :timeZone)`, is not read.  This results in wrong times being imported (and probably exported).

Additionally, times specified with inline timezones (2019-09-20T09:30:00+01:00 or 2019-10-05T13:30:00Z) are not treated correctly.

**Comment by arenzana** [comment]
Is there a way to override the timezone for a calendar in particular? Having this problem with a calendar I'm subscribed in in Gcal but published in GMT. I want it in Eastern time.

**Comment by telotortium** [comment]
Can you provide me an example of a calendar (preferably public) that I can use to reproduce your issue?

One difficulty is that the Org-mode timestamp format doesn't support any timezone information. Currently we convert from the timezone stored in the API response (contained in ISO 8601 format in`(plist-get data :dateTime)`) to the current system timezone in Emacs when retrieving, and vice-versa when updating.

**Comment by srgkoshelev** [comment]
I have experienced similar (same?) issue with an outlook calendar imported into google calendar (it's a long story). All of my appointments are shown 5 hours late which is consistent with CDT -5 time zone. 

It would be amazing if someone could look into this.

**Comment by cacocodix** [comment]
I used a temporary/ugly fix from [a comment at the unmaintained page](https://github.com/myuhe/org-gcal.el/issues/120#issuecomment-436060449) by @christoofar :
https://github.com/kidd/org-gcal.el/blob/744505832b34e07b44a5d97d8720b2d7492d7fc9/org-gcal.el#L243-L247
a `timeZone` header was added:
```
 :params
           (append
            `(("access_token" . ,a-token)
              ("singleEvents" . "True")
              ("timeZone" . "America/New_York"))
```
substitute  `America/New_York` with the TZ of your preference (on debian  I used `/usr/share/zoneinfo/`).

**Comment by srgkoshelev** [comment]
Are you a wizard?!

But, seriously, thank you so much! It works and does exactly what expected. I wonder if this can be pulled into the main repo.

Cheers,
Sergey.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by telotortium** [comment]
I'd be willing to accept this into the main repo. I'm looking for a good way to get the current time zone in IANA format (which Google Calendar requires): https://emacs.stackexchange.com/q/60031/17182.

**Comment by erichlf** [comment]
It seems to me the easiest solution would be to have the timeZone as a configurable variable.

**Comment by erichlf** [comment]
I found [this](https://www.gnu.org/software/emacs/manual/html_node/elisp/Time-of-Day.html)

**Comment by telotortium** [comment]
I'm leaning towards having timeZone be a configurable variable. If anyone wants to send a PR, that would be fine. Otherwise, I'll try to code this when I get some time.

**Comment by agenbite** [comment]
That'd be great, @telotortium... I can't get the "ugly fix" to work for me.

**Comment by christoofar** [comment]
> I used a temporary/ugly fix from [a comment at the unmaintained page](https://github.com/myuhe/org-gcal.el/issues/120#issuecomment-436060449) by @christoofar :
> https://github.com/kidd/org-gcal.el/blob/744505832b34e07b44a5d97d8720b2d7492d7fc9/org-gcal.el#L243-L247
> 
> 
> a `timeZone` header was added:
> ```emacs-lisp
>  :params
>            (append
>             `(("access_token" . ,a-token)
>               ("singleEvents" . "True")
>               ("timeZone" . "America/New_York"))
> ```
> 
> substitute `America/New_York` with the TZ of your preference (on debian I used `/usr/share/zoneinfo/`).

Glad to see my uglyfixes are still alive and kicking :-)
