### ISSUE TITLE
Suggestion: Don't store gcal creds in init.el file

### ISSUE THREAD

**Issue by jzohrab** [kidd/org-gcal.el#50]
Hello.  First off, this is great, thank you for picking up from the original repo from myuhe!

I push my init.el to github, and others do as well.  Storing creds in a publicly committed file is bad security, so I wrote a small function that reads from an (uncommitted) gcal-secret.json file, and use that instead.  Snippet:

```
;; Storing my creds in a secret file so I don't commit them here.
(require 'json)
(defun get-gcal-config-value (key)
  "Return the value of the json file gcal_secret for key"
  (cdr (assoc key (json-read-file "~/.emacs.d/gcal-secret.json")))
  )

(setq org-gcal-client-id (get-gcal-config-value 'org-gcal-client-id)
      org-gcal-client-secret (get-gcal-config-value 'org-gcal-client-secret)
      org-gcal-file-alist '(("jzohrab@gmail.com" . "~/Dropbox/org/schedule.org")))
```

If you'd like, I can make a PR to the README to suggest that other users do the same.  If not, feel free to close this PR.

Cheers! jz

**Comment by kidd** [comment]
For future reference I'm pasting the reddit post where this issue was discussed:  https://www.reddit.com/r/emacs/comments/d1ehpy/security_tip_if_you_push_initel_to_a_public_repo/ .

The more elispy way of doing what you propose here is using an elisp file to do the same. No need to use json :)

```elisp
;; secrets.el
(defvar my-client-id "1123")
....

;; init.el
(require 'my-secrets)
(setq org-gcal-client-id my-client-id)
```

**Comment by jzohrab** [comment]
Nice, that's neater.  I'm new to elisp, never considered doing it like that.  Should the file also be named `my-secrets.el` and be in my load path?

**Comment by kidd** [comment]
yep! updating my comment so it's fully working. Thanks!
