### ISSUE TITLE
Deleting events from the web does not work

### ISSUE THREAD

**Issue by chughtapan** [kidd/org-gcal.el#53]
Hi,

I followed the instructions and setup org-gcal. I am able to create events from my google calendar website and sync and changes to them from emacs. However, when I delete any event from the web interface, it still shows up in my org file.

What is the recommended way to delete events?

Thanks,
Tapan

**Comment by telotortium** [comment]
The current behavior is that, when an event is deleted on the server, it has no effect on the org file. `org-gcal-fetch` will retrieve events not currently in any Org file reachable via `org-id-goto` and update any events that have already been retrieved, but won't delete events deleted on the server from the org file. You can manually delete the Org headlines corresponding to deleted events.

Perhaps it would be worth modifying `org-gcal-sync-buffer` to prompt to delete headlines with deleted events.

**Comment by TobyHFerguson** [comment]
I can confirm both the original post and the response. It would be great to figure out how to be able to 'push' deletions from one end to the other - at the moment we are left having to keep calendars in synch manually :-( Its not always possible to know that an event has been deleted on the server, except by diligently comparing the google calendar by eye with the agenda, a rather painful task.

**Comment by telotortium** [comment]
Hi @TobyHFerguson, are you using the most up-to-date version? I believe the behavior you observed is what would be expected before #34, but the current behavior is what @chughtapan observed.

**Comment by jackkamm** [comment]
Is there an option to revert to the old behavior of deleting events that have been removed from the server? I use org-gcal to sync a shared calendar, and it's a hassle for me to have to manually delete events that my coworkers have modified or removed. Since updating my calendar is now filled with duplicate and old events.

**Comment by podiki** [comment]
Agree with above, this should be a configurable option (how to handle events deleted from server). Especially with Google Calendar being something often modified on e.g. a phone, this would help keep things straight. As of right now I'm only trying to use emacs to display the calendar, so my modifications are made on the web or via mobile and this is really necessary.

**Comment by telotortium** [comment]
Hi everyone, my life is getting busy at the moment, and will be until at least mid-January. If anyone wants to write a patch for this, I'd be more than willing to review it.

**Comment by kidd** [comment]
I'll try to take a stab at it but I've been out of the loop for some time now (wanting to get in again, but "life"...).

Happy to help driving it through while @telotortium is busy (thanks for the great job with the package!)

First I have to get my tokens working again anyway. :)

**Comment by gewthen** [comment]
I hope this gets address sooner or later. Not having it fully sync with Google Calendar means org-gcal is not reliable. I never really know if the meeting I see in my Agenda is still relevant for the day. I would suggest that the new behavior would not only prompt the user to confirm every deletion, but also recognize whether it is repeating and delete the whole series. However if the event has been modified in Org then we might not want to delete it.

For now I'll have to delete the Org files and fetch to get a full copy of the calendar. Though that means any notes attached for the events will need to live somewhere else.
