### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by bobberb** [kidd/org-gcal.el#6]
* Primary goal for the project

Attain MELPA reference to this github repo instead of myuhe's abandoned one.

**Comment by bobberb** [comment]
Thank you @kidd for bringing in pr60, 80, 101, 103, 108. Willing to test what is needed. Talk soon.

**Comment by kidd** [comment]
Hey! Thanks for having your master branch ready as a baseline for this new "official" repo :)

There's https://github.com/melpa/melpa/pull/5624 .

The only things I'd like to do before are:
-  testing #5 for the *-at-point
- Update docstrings.

**Comment by kidd** [comment]
we're live!

**Comment by bobberb** [comment]
Pop the champagne - it seems that if you give the community a little poke the job gets done.
