### ISSUE TITLE
"deferred error : (wrong-type-argument stringp nil)" when finishing org-capture

### ISSUE THREAD

**Issue by 9309** [kidd/org-gcal.el#62]
Hi,
After running org-capture with the following template
```
    (setq org-capture-templates
      '(("a" "Appointment" entry (file  "~/org/cal.org" )
	 "* %?\n :PROPERTIES:\n :calendar-id: myemail@gmail.com\n :END:\n:org-gcal:\n%^T--%^T\n:END:\n")))
```
and finishing the capture with C-c I get `deferred error : (wrong-type-argument stringp nil)`. I'd expected `org-gcal-post-at-point` to run correctly upon `org-capture-before-finalize-hook` but it seems like this is not working correctly. However, I can run `M-x org-gcal-post-at-point` inside the capture buffer before finalizing and it will work just fine.

Example org-capture input:
```
* Example
 :PROPERTIES:
 :calendar-id: myemail@gmail.com
 :END:
:org-gcal:
<2020-01-15 Wed 20:26>--<2020-01-15 Wed 20:26>
:END:

```

**Comment by kidd** [comment]
I don't know if code that runs in `orgg-capture-before-finalize-hook` has the needed context.  org-gcal is currently quite "context" dependent (buffer contents, surroundings, etc...) . 

I can't give you a full answer now, but it doesn't surprise me that it doesn't run well. 

It would be a nice addition to make it work in that situation though

**Comment by chenyanming** [comment]
Same issue here! It can not work with org-capture
![image](https://user-images.githubusercontent.com/3462132/74101928-adf71a80-4b79-11ea-9ef7-c9488204e390.png)

**Comment by vovav80** [comment]
Confirm the error: `org-gcal--format-org2iso: Wrong type argument: integerp, nil`

**Comment by telotortium** [comment]
You may be able to run it from `org-capture-after-finalize-hook`, if you run `org-capture-goto-last-stored` in order to place the point at the location of the captured event.

**Comment by 9309** [comment]
> 
> 
> You may be able to run it from `org-capture-after-finalize-hook`, if you run `org-capture-goto-last-stored` in order to place the point at the location of the captured event.

Indeed, this is a simple fix that works. I've made a pull request with this change.
