### ISSUE TITLE
Run org-gcal-fetch every 30 minutes/hour. Is the best way (run-with-timer)? Will it lock up emacs?

### ISSUE THREAD

**Issue by JSpenced** [kidd/org-gcal.el#65]
I wanted to run `org-gcal-fetch` every hour to update the calendar. Currently, it locks up my agenda for a couple seconds or more whenever I access it or refresh it if using `org-gcal-fetch` in an `org-agenda-mode-hook`.

I was wondering is the best way to run this in a `run-with-timer` and if so will it lock up my emacs every time it is run? Also, will it throw a bunch of errors if I am not connected to the internet.

Or any better suggestions just seeing how other people have it setup?

**Comment by JSpenced** [comment]
In case anyone was wanting to do this, I implemented it here.

I also erased the buffer before fetching. Seemed to work better for my setup. 
Also, I have a function that checks if there is an internet connection as well.

```
  (defun jj/org-gcal-archive-erase-then-fetch ()
	(interactive)
	(when (jj/internet-up-p)
	  (dolist (i org-gcal-fetch-file-alist)
		(with-current-buffer
			(find-file-noselect (cdr i))
		  (when org-gcal-auto-archive
			(org-gcal--archive-old-event))
		  (erase-buffer)
		  (org-gcal-fetch)))))

  (defun jj/org-gcal-fetch-when-idle-full ()
	(interactive)
	;; cancel this idle timer if it exists and hasn't run
	(cancel-function-timers 'jj/org-gcal-archive-erase-then-fetch)
	(run-with-idle-timer 21 nil 'jj/org-gcal-archive-erase-then-fetch))

  ;; Run once in emacs-startup-hook as well
  (run-with-timer (* 363 60) (* 360 60) 'jj/org-gcal-fetch-when-idle-full)
```

**Comment by arnavsharma93** [comment]
Code for the internet check function if someone is interested.
```
  (defun jj/internet-up-p (&optional host)
    "Checks if the internet is up by pinging google."
    (= 0 (call-process "ping" nil nil nil "-c" "1" "-W" "1"
                       (if host host "www.google.com"))))

```
