### ISSUE TITLE
Events are not removed if a recurrence is deleted

### ISSUE THREAD

**Issue by aaronjensen** [kidd/org-gcal.el#81]
I don't know the exact repro, but I had a recurrence that went into the future (meeting every workday). That recurrence was removed from google calendar, but they never disappeared from org-gcal. 

I believe this happened before the sync tokens were implemented, and it's still happening. I have to purge my output org files and clear sync tokens before refreshing to guarantee I only have current events visible.

**Comment by telotortium** [comment]
I'm looking into this. Hope to have a fix ready soon.

**Comment by aaronjensen** [comment]
Thanks for the quick fix. I'll let you know if I run into anything else.
