### ISSUE TITLE
Pull no push

### ISSUE THREAD

**Issue by cvanelteren** [kidd/org-gcal.el#90]
Hi,
I have followed the instructions to the letter and I am able to pull the calendar in google. However I am not able to push to this calendar. I receive no errors yet any schedule event in local agenda is not updated in the buffer. Are there any standard debug steps I can follow?

```
Events fetched into
~/orgfiles/gcal.org
Completed event fetching .
Events fetched into
~/orgfiles/gcal.org
```

`post-at-point` fails however with error 404. 

The readme states to put the app as _other_ however this is not available on the dashboard, _desktop app_ is used instead. Both api for caldev as well as Calendar are active and show activity.

**Comment by telotortium** [comment]
Can you send me the Org mode headline (redact whatever you need to)?

**Comment by cvanelteren** [comment]
I am not entireley sure what you mean

I have a headline as follows

```
* Some topic I need to discuss

Alternatively I have some 
TODO: do this thing

```

Then I schedule these is in spacemacs using `SPC m s` but nothing is put into the calendar.

**Comment by telotortium** [comment]
File #91 to handle this.

**Comment by cvanelteren** [comment]
Thanks @telotortium. The issue seems to imply that with the correct tags the push would work? Is there any wiki out there that would show me how to push a schedule item into my google calendar? I have tried copying existing pulled ones but it doesn't update it on the web (error 403). 

Digging deeper it seems to come from setting up the authentication. Full control to the calendar API requires authentication of the app. But the process requires an URL, which in the case of org-cal syncing is a bit overkill...

**Comment by telotortium** [comment]
#92 should fix this. Can you update to the latest master and try again?

**Comment by cvanelteren** [comment]
Yes it works! Awesome, thanks!
