### ISSUE TITLE
deferred error : (invalid-function (listp x))

### ISSUE THREAD

**Issue by tgpfeiffer** [kidd/org-gcal.el#93]
My (outdated) version of org-gcal stopped working today with 400 errors, so I upgraded to 20200609.1915 and also updated all other packages. When running `org-gcal-fetch` I get the error
> deferred error : (invalid-function (listp x))

with the following details:

```
Debugger entered--Lisp error: "deferred error : (invalid-function (listp x))"
  message("deferred error : %S" (invalid-function (listp x)))
  deferred:exec-task(#s(deferred :callback #f(compiled-function (x) #<bytecode 0x485b9d>) :errorback deferred:default-errorback :cancel #f(compiled-function (x) #<bytecode 0x15e8e25>) :next nil :status nil :value nil) ok nil)
  deferred:worker()
  apply(deferred:worker nil)
  timer-event-handler([t 24305 37693 928132 nil deferred:worker nil nil 401000])
  read-event(nil t 2)
  sit-for(2)
  execute-extended-command(nil "org-gcal-fetch" "org-gcal-fee")
  funcall-interactively(execute-extended-command nil "org-gcal-fetch" "org-gcal-fee")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

The `deferred` version is 20170901.1330, Emacs is 26.3. The local calendar org file is not updated due to this error.

**Comment by tgpfeiffer** [comment]
Is there anything I can do to help fixing this?

**Comment by telotortium** [comment]
Sorry for taking a while to get back to this.

Can you reliably reproduce this? There's one place in my code that contains `(listp x)`:

```
        (when-let
            ((x (gethash calendar-id org-gcal--sync-tokens))
             ((listp x)))
          x)
```

However, I tested this locally and it works whether `(listp x)` is or is not enclosed in an additional pair of parentheses. That is, both

```
(when-let
    ((x '(1 2 3))
     ((listp x)))
  x)
```

and

```
(when-let
    ((x '(1 2 3))
      (listp x))
  x)
```

return `(1 2 3)`

**Comment by ssinari** [comment]
I am having a similar issue but with latest gcal:
#s(deferred #[257 "ÂÀÁ\"" [#[257 "@AÀ\0À\0Å ÁÂÆÇÈ\"ÉÊËÌ	BÍBÎÏÐÑ BÒÓ BÔBBBBBBÕÖ&²×ØÙÚÛÜ		\"Ý\"Þß%\"²×ØÙàÛÜ\"á\"âã%\"²×ØÙäÛÜ
\"å\"æç%\"²×ØÙèÛÜ	\"é\"êë%\"²²" [nil t nil org-gcal-events-url org-gcal-client-secret org-gcal--get-access-token nil request-deferred format :type "GET" :params ...] 19 "

(fn X)"] ("{MY GMAIL}" . "{MY GCAL.ORG FILE}") deferred:call-lambda] 4 "

(fn X)"] deferred:default-errorback #[257 "Á!À¢Â:\0@²Ã!A²\0Â" [(...) deferred:default-cancel nil deferred:cancel] 5 "

(fn X)"] nil nil nil)
[error] request--callback: peculiar error: 400
[error] request-default-error-callback: https://www.googleapis.com/calendar/v3/calendars/{MY GMAIL}/events error
(error http 400)

deferred error : (error "Got error 400: (error http 400)")

The client ID and secret are correct. The token is refreshed.
org-gcal version:
 ("org-gcal.el" . "6821e349673e9ba8d7ae7b84789f931889273dc0")
This is github commit hash.
Any help is appreciated.

**Comment by tgpfeiffer** [comment]
This has resumed to work fine for me with org-gcal (20200809.2137) and org-mode 9.3.7 in Emacs 26.3, so let me close this issue. (Please reopen if you disagree.)
